apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: monitoring
spec:
  type: NodePort   # Use NodePort if LoadBalancer unsupported
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: django
