apiVersion: v1
kind: Secret
metadata:
  name: django-env-secret
  namespace: monitoring
type: Opaque
stringData:
  POSTGRES_DB: fleetdb
  POSTGRES_USER: roy77
  POSTGRES_PASSWORD: asdf1234@77
  PYTHONUNBUFFERED: "1"
  POSTGRES_HOST: db
  STRIPE_SECRET_KEY: "sk_test_51R2EHqFxSoY5Rjyor0IeGElOkgFZMziWh7YMbEydw7Xrby1GlzZijsW3JXw7sqhTRWTKKTIsG4xxPXhlCEQd5dRU00zvsQANcy"
  STRIPE_PUBLIC_KEY: "pk_test_51R2EHqFxSoY5RjyoISdnIQZkHvt6LmxJdpdEVxG3MYvlhbkgOQPzTUck2pZtcbKLQQKasG7VHZNkzMH7bCv6XmC600QlbooiKJ"
  STRIPE_WEBHOOK_SECRET: "whsec_..."
  POSTGRES_EXPORTER_DSN: "postgresql://roy77:asdf1234@77@postgres:5432/fleetdb?sslmode=disable"